FROM python:bookworm

COPY ./* /

RUN pip install -r requirements.txt

RUN python -m nltk.downloader punkt_tab

RUN apt-get update

RUN apt install calibre -y

ENV PATH="$PATH:/opt/calibre"

CMD ["sh"]